call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'ntpeters/vim-better-whitespace'
Plug 'mileszs/ack.vim'
Plug 'rust-lang/rust.vim'
Plug 'vim-airline/vim-airline-themes'
Plug 'romainl/Apprentice'
call plug#end()

colorscheme apprentice

set nocompatible        " I really don't care about being VI compatible

syntax enable

set autoindent
set softtabstop=2
set tabstop=2
set shiftwidth=2
set expandtab
set ts=2

"""" UI Config
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]
set showcmd             " show command in bottom bar
set cursorline          " highlight current line

set wildmode=list:longest
set ignorecase
set smartcase

filetype on
filetype indent on      " load filetype-specific indent files
filetype plugin on      " load filetype-specific plugins

set t_Co=256

" Bells suck, quash them or make them go away
set noerrorbells
set vb t_vb=""

" Search as I type
set hlsearch
set incsearch

"""" Folding

set foldenable
set foldlevel=9
set foldmethod=syntax
set foldtext=getline(v:foldstart)
map <TAB> za

let mapleader=","
map <Leader>n :set number!<CR>
map <Leader>p :set paste!<CR>

" Set terminal title
set title
set history=1000

set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" set backupdir=~/.tmp
" set directory=~/.tmp
" set undodir=~/.tmp

